### ISSUE TITLE
Batch Metadata update

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#103]
**Description:** Process for updating many workbench metadata files at once. Sent email to Jordyn to see if he has any tools already made. https://desktop.arcgis.com/en/arcmap/latest/manage-data/metadata/editing-metadata-for-many-arcgis-items.htm ^This could be a possible solution.
**Category:** Metadata only
**Workspace:** 
**% Complete:** 20%

**Comment by gfuellingwa** [comment]
Duplicate issue
