### ISSUE TITLE
PHS Data Update

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#104]
**Description:** PHS update
**Category:** ESO SDE Data -update
**Workspace:** I:\DATA\ExternalData\DFW\PHS
**% Complete:** 90%

**Comment by kechinn** [comment]
SharePoint Progress Log:
Fuelling, Garrett (1/5/2021 9:42 AM): Data updated, metadata dates updated, new layer file made for species points. No update needed for taxonomy and federal class layers. New layer made for species archive(two species added). No update needed for occurrence polygon .lyr file.
Alton, Jesse (10/29/2020 10:22 AM): Requested data from WDFW.  Waiting on invoice to purchase.

**Comment by gfuellingwa** [comment]
ETL ran and data on WB
