### ISSUE TITLE
DAHP Q4 Update

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#105]
**Description:** Statewide quarterly update (Q4)
**Category:** 	Extnrl SDE Data -update
**Workspace:** I:\DATA\ExternalData\DAHP\DAHP_20201029\Statewide
**% Complete:** 90%

**Comment by kechinn** [comment]
SharePoint Progress Log:
Fuelling, Garrett (12/30/2020 7:16 AM): Metadata updated and data ready for ETL
Alton, Jesse (11/2/2020 11:59 AM): New data download from DAHP on 11/2
Alton, Jesse (10/29/2020 10:19 AM): Downloaded most recent data from DAHP.

**Comment by gfuellingwa** [comment]
ETL ran and data is good.
