### ISSUE TITLE
Major Public Lands

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#106]
**Description:** Update dataset on the workbench Contacting DNR if there has been any update since Nov of 2017.
**Category:** 	Extnrl SDE Data -update
**Workspace:** 
**% Complete:** 30%

**Comment by kechinn** [comment]
SharePoint Progress Log:
Fuelling, Garrett (12/1/2020 9:45 AM): Email sent to DNR
Fuelling, Garrett (11/24/2020 3:04 PM): Contact electronic mail address: elizabeth.eberle@dnr.wa.gov

**Comment by gfuellingwa** [comment]
DNR will update in 2021
