### ISSUE TITLE
Habitat Connectivity Structures Web App Builder 2020

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#107]
**Description:** Annual update for Workbench, WSDOT GeoPortal Habitat Connectivity web map.
**Category:** ESO SDE Data -update
**Workspace:** 
**% Complete:** 70%

**Comment by kechinn** [comment]
SharePoint Progress Log:
Fuelling, Garrett (9/8/2020 7:48 AM): Wait for new web layer with attachments
Fuelling, Garrett (5/27/2020 5:16 PM): Waiting for ITD to fix/make new layer with attachments. Waiting to remake Queries in case ITD provides a new feature layer.
Fuelling, Garrett (4/16/2020 9:56 AM): New data needed, minor symbology updates requested (grouping of species by species type, collapsible headers.)
Fuelling, Garrett (2/11/2020 1:14 PM): Data prepped on EnviDataEdit. Changed some fields to match the template provided fields. Waiting on response from Kelly to confirm symbology of new data and the currentness of data.
Alton, Jesse (2/10/2020 9:35 AM):
Fuelling, Garrett (1/7/2020 1:34 PM): Resymbolize crossings, eliminate any species not being used, and regroup by animal type
Fuelling, Garrett (1/3/2020 3:56 PM): Species expressions written. Need to embed the attachment carousel still.
Fuelling, Garrett (1/2/2020 5:09 PM): Need to write all of the species toggle expressions in Web App Builder
Fuelling, Garrett (12/30/2019 11:09 AM): Application is not working on different size screens (widgets not displaying properly.)
Fuelling, Garrett (12/20/2019 4:30 PM): Kenzie provided updated data. Need to solve "staging" error when trying to upload to AGOL.
Alton, Jesse (12/20/2019 4:15 PM): Garrett is lead designer and will work with Kenzie and data content and UI.
Alton, Jesse (6/10/2019 11:02 AM):
Alton, Jesse (4/18/2019 8:56 AM): Will work with Glen to update attachments. Data will be hosted on AGOL to drive story map and web map products.
Alton, Jesse (2/5/2019 1:31 PM):Alton, Jesse (7/24/2018 9:31 AM): Working with Glen to update attachments. 
Alton, Jesse (5/10/2018 4:39 PM): Back on track. Will review data and prepare for workbench.
Alton, Jesse (1/31/2018 4:34 PM): Kelly near completion.  Need to add CSIID. Will post to 17P in the next few weeks.
Alton, Jesse (8/2/2017 9:22 AM): Received updated HabCon structures from Kelly.  Will review and prep for WB. Need to discuss and finalize photo attachments.
Alton, Jesse (7/25/2017 5:37 PM):
Lanzer, Elizabeth (7/12/2017 11:14 AM): Updated for FY17-19.
Alton, Jesse (6/7/2017 3:07 PM): Data requested.  Kelly needs time to review and update existing data.

**Comment by kechinn** [comment]
This could potentially be part of a GitHub Project if you wanted, since there are different components (i.e. GIS WB Update and a AGOL web map). Alternatively, feel free to create a check list in this issue.

**Comment by gfuellingwa** [comment]
Bringing this back to attention. Email sent to Glen to ask about if he still wants this. Might need to ask Stacey Plumley to help with getting correct data into AGOL

**Comment by gfuellingwa** [comment]
Glen is going to edit camera field, and then we will set up a meeting with Stacey to finalize the app for deployment.

**Comment by gfuellingwa** [comment]
This is being revisited, Katrina may do most of the work but I will help at least with showing what I made previously,
