### ISSUE TITLE
DoH Data Update

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#108]
**Description:** Check on status of DoH on workbench.
**Category:** Extnrl SDE Data -update
**Workspace:** 
**% Complete:** %

**Comment by gfuellingwa** [comment]
Check on current data, and also wait for Justin Zweifel to let us know about other datasets from DOH

**Comment by gfuellingwa** [comment]
Sent email to Justin asking about this

**Comment by gfuellingwa** [comment]
Elizabeth Lanzer is acquiring the data in that web map. Going forward with updating the data currently on the WB

**Comment by gfuellingwa** [comment]
Ask Team if anyone else they know is using this data, might be able to be archived.
