### ISSUE TITLE
Impervious Surfaces/Canopy Coverage and Land Cover - Western Washington

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#109]
**Description:** Add new 2006 impervious surface data from ecology and 2015 king county SDE edit.  Replace Land Cover data with 2011.  Leave "Impervious Surface and Canopy Cover Change in Western Washington 1991-2001"
**Category:** Extnrl SDE Data -update
**Workspace:** 
**% Complete:** 80%

**Comment by kechinn** [comment]
SharePoint Progress Log:
Alton, Jesse (7/9/2020 2:17 PM): Need to follow-up with Jordyn on status.
Alton, Jesse (12/20/2019 4:12 PM):
Fuelling, Garrett (9/18/2019 8:34 AM): Western Washington Land Cover data prepped and email sent.
Alton, Jesse (9/12/2019 9:27 AM):
Alton, Jesse (9/12/2019 9:22 AM): Not sure who the customer is for impervious.  Kelly's group use a different method for calculating % impervious.  I'll talk with Jordyn to see what level of effort we need to make with these datasets. Let's cont. to prep email and data for "Land Cover".
Alton, Jesse (9/10/2019 11:25 AM):

**Comment by kechinn** [comment]
@gfuellingwa Is this related to #97?

**Comment by jesse-WSDOT** [comment]
Garrett investigating 2011 Landsat USGS data to replace impervious and Land Cover

**Comment by gfuellingwa** [comment]
Downloaded 2016 Impervious Surface and Canopy Cover. Used Zonal Statistics to add new field of mean Impervious and Canopy to the existing feature class. new .lyrs made as well. Need to update Metadata and stage in prep environment

**Comment by jesse-WSDOT** [comment]
ESO QA Approved

**Comment by gfuellingwa** [comment]
Email sent to Jordyn for update

**Comment by kechinn** [comment]
@gfuellingwa I'd like to check back in on this with you at some point. Was the Western Washington Land Cover 2006 supposed to be replaced or updated? It is still on the WB with no updates to metadata. Looks like Western WA Impervious Surface Percentage 2016 was updated, but I'm a little confused about the metadata (might want to update again).

**Comment by gfuellingwa** [comment]
I think what we ended up doing was putting the 2016 (most recent) version of the National Land Cover Database dataset(clipped to the state outline) on the workbench.

I guess that would mean we don't really need to keep the 2006 Western WA dataset on the workbench, as I assume the 2016 version will be sufficient
