### ISSUE TITLE
Stormwater Retrofit

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#114]
**Description:** 2019 Stormwater Retrofit update.  New SDE data for the workbench.  This includes LRS 2018 update and segment geometry/topology verification.  
**Category:** ESO SDE Data -new
**Workspace:** I:\DATA\ESOData\StormwaterRetrofitProrities
**% Complete:** 60%

**Comment by kechinn** [comment]
SharePoint Progress Log:
Johnson, Tanya (12/18/2019 10:14 AM): @gfuellingwa Garrett okay with new .lyr
Alton, Jesse (9/12/2019 5:04 PM): Revisit with Sheena and Garrett on Retrofit update for workbench.
Alton, Jesse (2/6/2019 10:22 AM): Waiting of customer to update Storm water attributes.
Alton, Jesse (7/3/2018 3:27 PM): Processed ARM values and added WSDOT LRS standardized field names.  This includes Corridor ID field.  Waiting on customer for metadata and verification for zero value length features (10ct).

**Comment by gfuellingwa** [comment]
This was brought up in a 2/3/21 meeting with Policy Branch

**Comment by kechinn** [comment]
@kechinn Contact Sheena to check-in on status of retrofit layer
