### ISSUE TITLE
DNR Watercourses, DNR Waterbodies Update 2021-01-27

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#119]
DNR Watercourses, DNR Waterbodies is going to change on 2021-01-27

Here's the summary of what is expected to happen:
The old service that was in use has been replaced by a new service.

Additional URL references:

Use the link below to access the dashboard to review changes, logon as you normally would for AGOL.  If that doesn't work, login to the  AGOL WA GIS Change Management Group to view Agency dashboard.

https://www.arcgis.com/apps/opsdashboard/index.html#/7d2ecfd0a11e48f3b421bcfae0d45d22

I'll have to update the RMEC GeoPortal.

**Comment by jesse-WSDOT** [comment]
Downloaded DNR WC data for geo.wa.gov.  Prep for workbench.

**Comment by jesse-WSDOT** [comment]
Data on Workbench
