### ISSUE TITLE
Hydrology Program Proposed Flights 

### ISSUE THREAD

**Issue by jesse-WSDOT** [wsdot-eso/Environmental-Information#12]

**Comment by jesse-WSDOT** [comment]
Glacier Creek Fight Scheduled - Oct 14-16 
Customer - Cygnia Rapp 
Logistics List (feel free to add or check off)

- [ ] GPS Signal Test
- [ ] Network Coverage R2 RTK (T-Mobile might work)
- [ ] Weather Window 
- [ ] Wind 
- [ ] Safety Hazards  
- [ ] Accommodations (Airbnb)
- [ ] Car Reservation 
- [ ] Garrett Jackson (Available Oct 14-15) 
- [ ] Justin S (Regional Staff Support)
- [ ] GCPs Targets 
- [ ] Tony Bush??

**Comment by kechinn** [comment]
Proposed Glacier Creek Flight Scheduled Oct 28-29
