### ISSUE TITLE
Noise Walls 2021

### ISSUE THREAD

**Issue by gfuellingwa** [wsdot-eso/Environmental-Information#125]
**Description:**
**Category:**
**Workspace:**
**% Complete:** %

Update Noise Walls on the WB. Waiting for Jim to send list of new data(should be within a month.)

**Comment by gfuellingwa** [comment]
Reminder email sent to Jim about the status of this.

**Comment by gfuellingwa** [comment]
Jim is still working on updates

**Comment by gfuellingwa** [comment]
Jim sent me the new data for the 2021 update

**Comment by gfuellingwa** [comment]
Jim said that he will have another round of updates by the end of the month. Going to make the updates that he sent in the first round and then wait for the next round of updates.

**Comment by gfuellingwa** [comment]
Need to have a quick meeting with Jim to talk about a few barriers that threw an error when mapping to the LRS.

**Comment by gfuellingwa** [comment]
Jim gave corrections, need to make those and then do any data cleanup.

**Comment by kechinn** [comment]
@kechinn Reminder to move this to EIP GIS Workbench archive folder
