### ISSUE TITLE
Environmental Justice Census Demographics

### ISSUE THREAD

**Issue by gfuellingwa** [wsdot-eso/Environmental-Information#127]
This dataset can be deleted from the workbench, as confirmed during Policy branch meeting on 2/3/2021

**Comment by gfuellingwa** [comment]
Email sent to Jordyn for deletion.

**Comment by gfuellingwa** [comment]
Email Received by Jordyn Mitchell:

This is data used by the Alpaca application.  The layer file in your business area can be removed but not the underlying data.  I’ll work on that soon as I can.
Hope that makes sense
Jordyn

**Comment by gfuellingwa** [comment]
Jordyn removed the .lyr from the workbench. Note: the data is still being used but is maintained by the NW region staff.

**Comment by kechinn** [comment]
@kechinn Make sure this gets placed in workbench archive
