### ISSUE TITLE
Right of Way Dataset

### ISSUE THREAD

**Issue by gfuellingwa** [wsdot-eso/Environmental-Information#131]
Policy branch requested this on 2/3/21, Tanya is sending email.

**Comment by Tjohnson-WSDOT** [comment]
Talked with Jeff Graham and he is working with Jordyn to get a data set that will use SR and link to the ECM plan sheets that will show the ROW. It should be ready in about a month. There will not be a ROW layer

**Comment by kechinn** [comment]
Check in with Jordyn
