### ISSUE TITLE
Agricultural Crops by Section

### ISSUE THREAD

**Issue by gfuellingwa** [wsdot-eso/Environmental-Information#141]
Stormwater did not claim ownership of this dataset, determine if there is anyone, if not, remove from WB. 
**Description:**
**Category:**
**Workspace:**
**% Complete:** %

**Comment by Tjohnson-WSDOT** [comment]
emailed Garrett Jackson to see if his group uses this

**Comment by Tjohnson-WSDOT** [comment]
Hydrology also didn't claim this dataset. It can be marked for removal.

**Comment by Tjohnson-WSDOT** [comment]
Mark for deletion 3/4/2021

**Comment by kechinn** [comment]
Send email to Jordyn to delete, archive layer from I to V

**Comment by gfuellingwa** [comment]
Jordyn confirmed deletion
