### ISSUE TITLE
Fish Passage - Web App Builder Use Case 

### ISSUE THREAD

**Issue by jesse-WSDOT** [wsdot-eso/Environmental-Information#144]
Stream Restoration Request: Web App Builder Use Case 

Description: Migrate GeoPortal Fish Passage site to new and improved WAB or Experience Builder platform
Category: 
Workspace:
% Complete: %

Develop and review both AGOL and Portal platform

https://www.esri.com/en-us/arcgis/products/arcgis-experience-builder/overview
https://developers.arcgis.com/web-appbuilder/

**Comment by jesse-WSDOT** [comment]
Assigned to Garrett:
Developed web application with AGOL ESO Admin account using Experience Builder platform

**Comment by gfuellingwa** [comment]
Planning to show draft version to Molly and Kathy, try to implement the QR code and also make it mobile friendly.

**Comment by gfuellingwa** [comment]
Need to publish both uncorrected and corrected barriers as Feature Services. Look into filter query as a site ID search feature(user input), add regions, buffering.

**Comment by gfuellingwa** [comment]
Sent email to have another planning meeting to iron out details.

**Comment by gfuellingwa** [comment]
Had meeting, Molly and Kathy seem happy with the result. next step is to talk to Stacey about the web app, and for Molly and Kathy to show it to their group.

**Comment by gfuellingwa** [comment]
Stacey and Eric were very supportive of replacing the Geoportal app with the web app builder app. Waiting on Stacey to send Arcade expressions over to implement report building, photos, species code, and the state route mile query widget

**Comment by gfuellingwa** [comment]
Action Items for me:

1. Finish any documentation in Info tab
2. Fix any minor symbology issues(blue diamonds not zooming)
3. Contact Stacey about putting a redirect link on the Geoportal app to the WAB builder version

Katrina will send me new layers to add to the web map.

**Comment by gfuellingwa** [comment]
Action items for me:
 
Clean up/add to Info widget
Figure out NHD River/Major Rivers. I just put that service you sent in, and it is very detailed. There may be some type of definition query we can do to make it more accurate to the major Rivers data on the WB?
Set up meeting with Jordyn, you, and Stacey to talk about Data storage for the Design plans
 
For Katrina:
 
Metadata for design plans
Prepare to talk about the schema for those datasets to jordyn

**Comment by gfuellingwa** [comment]
App is ready for first version release

**Comment by gfuellingwa** [comment]
Shared with the public.
