### ISSUE TITLE
Upgrade Existing Storm Water Feature layers to have attachments

### ISSUE THREAD

**Issue by gfuellingwa** [wsdot-eso/Environmental-Information#146]
**Description:**
**Category:**
**Workspace:**
**% Complete:** 0%

Add attachments to SW Features FC's on the Workbench

**Comment by kechinn** [comment]
Schedule meeting with Jana Crawford, Cory Simon and Nick Hehemann to discuss schema changes, and future outlook for this project (i.e GIS Workbench, web service?)
