### ISSUE TITLE
Stormwater Story Map 

### ISSUE THREAD

**Issue by jesse-WSDOT** [wsdot-eso/Environmental-Information#158]
[RE_ Story Maps.pdf](https://github.com/wsdot-eso/Environmental-Information/files/6353199/RE_.Story.Maps.pdf)

**Description:**
**Category:**
**Workspace:**
**% Complete:** %

Request from Jana to build and design Story Map 
[RE_ Story Maps.pdf](https://github.com/wsdot-eso/Environmental-Information/files/6353202/RE_.Story.Maps.pdf)

**Comment by jesse-WSDOT** [comment]
sent follow up email to jana

**Comment by kechinn** [comment]
@jesse-WSDOT Revisit in August-September
