### ISSUE TITLE
Wetland Mitigation Site Boundary Update

### ISSUE THREAD

**Issue by Tjohnson-WSDOT** [wsdot-eso/Environmental-Information#165]
**Description:** Update the Wetland Site Boundary data
**Category:** Wetland
**Workspace:** I/data/eso/wetlands
**% Complete:** 100%

Did a truncate/load so no data schema change but Jenni wants the name changed from Wetland Mitigation Site Boundary to 
Environmental Restoration Sites.

I put the data on EnviroDataEdit."WSDOT\JOHNSTA".EnvironmentalRestorationSites

**Comment by jesse-WSDOT** [comment]
Okay. I'll work with Jordyn on the SDE ETL and get the layer name changed.

**Comment by Tjohnson-WSDOT** [comment]
Now on workbench as Environmental Restoration Sites.
