### ISSUE TITLE
TSG excel file

### ISSUE THREAD

**Issue by Tjohnson-WSDOT** [wsdot-eso/Environmental-Information#183]
**Description:**  export attribute data to excel file for biology Group
**Category:**   Fish and Wildlife
**Workspace:**
**% Complete:** %

**Comment by jesse-WSDOT** [comment]
Follow up with Jeff on TSG

**Comment by kechinn** [comment]
Jeff emailed TSG 2022 updates, excel attachment forwarded to wsdotesogis email

**Comment by kechinn** [comment]
Forwarded updated TSG road segment data excel spreadsheet from Jeff to the wsdotesogis email

**Comment by gfuellingwa** [comment]
Start working on new workflow, and scripting out it instead of doing manually through the UI.

**Comment by gfuellingwa** [comment]
Have final feature classes for the four layers of interest with the simpler workflow. Meeting scheduled to show Jeff these new layers.

**Comment by gfuellingwa** [comment]
Sent TSG road segments to Jeff and Kim for review.

**Comment by gfuellingwa** [comment]
Given TSG update spreadsheet.

**Comment by gfuellingwa** [comment]
Wait for BMP field update

**Comment by gfuellingwa** [comment]
Confusion cleared up on Kim's duties, she will go back and review and make a new spreadsheet for me.

**Comment by gfuellingwa** [comment]
Need to change title in ToC but data is in workbench

**Comment by gfuellingwa** [comment]
New file sent to Jordyn to fix Representation file name
