### ISSUE TITLE
Update National Wetland Inventory (NWI) layer

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#257]
Tara Stone said that the NWI Mapper tool on the FWS website is different than layer on the GIS WB. Need to determine if it needs updating. Is it a service?

https://www.fws.gov/program/national-wetlands-inventory/wetlands-mapper

**Comment by jesse-WSDOT** [comment]
NWI Wetaland records have changed since  update.  
Downloaded 2020 data from FWS.  Ready to prep for Workbench. 

![image](https://user-images.githubusercontent.com/52254628/197852081-4ce1aa1f-e64d-45f4-8f9c-4feaa66130ad.png)

**Comment by jesse-WSDOT** [comment]
Data ready for Jordyn on 17P

**Comment by Tjohnson-WSDOT** [comment]
Used truncate & load process to update NWI wetlands. There's no schema change.

**Comment by jesse-WSDOT** [comment]
Data ready for Jordyn

**Comment by Tjohnson-WSDOT** [comment]
Check and update now on the workbench.
