### ISSUE TITLE
DAHP Q3 2022

### ISSUE THREAD

**Issue by jesse-WSDOT** [wsdot-eso/Environmental-Information#260]
DAHP ready on I Drive

**Comment by gfuellingwa** [comment]
Need to coordinate updating the new schemas of data in the edit environment to match new schema of DAHP update.

**Comment by jesse-WSDOT** [comment]
Can we close this task?

**Comment by gfuellingwa** [comment]
> 

Not yet, still waiting on finalization of schema change
