### ISSUE TITLE
Wetland 2023 field season GPS collection

### ISSUE THREAD

**Issue by Tjohnson-WSDOT** [wsdot-eso/Environmental-Information#277]
Prepare tablets with background files and update data dictionary. Post Process data after collection.

**Comment by Tjohnson-WSDOT** [comment]
prepared background files for GPS.

**Comment by Tjohnson-WSDOT** [comment]
Jesse updated 2nd RC to "CM" grade. Prepared tablet tor work with Equipment ready to be picked up by wetland staff.

**Comment by jesse-WSDOT** [comment]
closing
