### ISSUE TITLE
Request to update Air Quality GIS Layer

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#305]
Karin Landsberg and Lindsay Taylor reached out to state that the Air Quality layers in the GIS WB are out of date, and need this data to be updated ASAP so that region folks can determine if their project needs additional air quality consideration or not. The current layer shows Yakima still being in maintenance area for CO-- which ended 12/31/22.

**Comment by gfuellingwa** [comment]
Should we use the services of the data or should I download them for use in the workbench?

**Comment by jesse-WSDOT** [comment]
If the data service a "feature service" (not map services) the I vote service for the workbench.  All you need to do is create the layer to share with Jordyn - pointed to the URL Rest End Point

**Comment by gfuellingwa** [comment]
Need to coordinate about Metadata for Air Quality

**Comment by gfuellingwa** [comment]
Email sent to check back in and see if this is resolved

**Comment by gfuellingwa** [comment]
Lindsay emailed back right away and said Ecology will update their data within the month. Closing task
