### ISSUE TITLE
Environmental Mitigation Sites Update

### ISSUE THREAD

**Issue by Tjohnson-WSDOT** [wsdot-eso/Environmental-Information#306]
Update the Environmental Mitigation Sites layer for the Workbench

**Comment by Tjohnson-WSDOT** [comment]
Sent to Jordyn for workbench,

**Comment by Tjohnson-WSDOT** [comment]
On workbench. Ready for Map center

**Comment by jesse-WSDOT** [comment]
Sent Stacey new RMEC GeoPortal APRX w/ added Mitigation Sites data.  On standby until she returns from vacation.
