### ISSUE TITLE
GIS Request to Determine Wetland Mitigation Site Proximity to Other Boundaries

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#308]
From: Andrews, Kristen <[AndreKr@wsdot.wa.gov](mailto:AndreKr@wsdot.wa.gov)> 
Sent: Thursday, June 1, 2023 10:20 AM
To: Chinn, Keisha <[chinnk@wsdot.wa.gov](mailto:chinnk@wsdot.wa.gov)>
Cc: Alton, Jesse <[AltonJe@wsdot.wa.gov](mailto:AltonJe@wsdot.wa.gov)>
Subject: GIS exercise
Importance: High

Hello Keisha,

I have a mapping exercise I would like to know if you or someone on your team can help me with. We are looking at the mitigation sites that WSDOT owns and manages (closed sites in long term maintenance) and their proximity to tribal lands, public parks (county and city), other public lands like state parks or national parks, forest service. 

This is in response to the decreased funding in preservation and maintenance agency wide. I was contacted by Ahmer and Kevin Workman in real estate services with a question of what do we do with these properties and how do we manage them with no funding. One of our brainstorming ideas was to see if our mitigation properties bordered these public or tribal lands. This is with the idea that maybe certain properties may be attractive to other municipalities for preservation purposes and we could either give or sell them the properties with a long term easement. We are allowed by law to actually give property back to the tribes. So I think these tribal adjacent properties would be a priority. 

I was able to download the layers that I thought were applicable and view them but I don’t know how to come up with a list of these properties. Is there some sort of tool that could be used to come up with this information? Do you or is there someone on your team that knows how to run this kind of query on ArcPro? 

Let me know what you think or if you would like to meet and discuss this. 

Thank you!

Kristen Andrews (she/her)
Wetland Program Manager
WSDOT | Headquarters Wetland Program
Mon-Thurs 6:30am to 5:00pm
Office 360-570-6640 | Cell 360-584-4285
[Kristen.Andrews@wsdot.wa.gov](mailto:Kristen.Andrews@wsdot.wa.gov)

**Comment by kechinn** [comment]
Kristen mentioned in follow up email that it would be nice if they had some information by a meeting tomorrow, Tuesday at 3pm, but realizes this request was last minute and may not be done by then. Still marking as ASAP, but no issue if no one can pick up and finish before that deadline.

**Comment by gfuellingwa** [comment]
Is it just going to be something like finding the sites that are in a buffer of other layers? I have some meetings this afternoon but could work on it between them

**Comment by kechinn** [comment]
Could do a buffer, but Kristen didn't mention a search radius, so could run Generate Near Table tool to grab distances from each polygon to nearest feature (I realize this may not help if there are multiple near features though, so not sure how to fix this unless you found distance to all features and then somehow pare it down or give to Kristen as is). Imagine we could give Kristen a map product showing only mitigation sites with status "closed", along with other boundaries, and attribute table showing distance. Could even export table to excel to show a list of all and Kristen could go through to determine which she deems close enough to matter.

**Comment by gfuellingwa** [comment]
Will reach out again tomorrow and should be able to get a result by 3 PM
