### ISSUE TITLE
GIS Request for Mapping Fish Passage Sites

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#312]
From: Wiltse, Wayne <[WiltseW@wsdot.wa.gov](mailto:WiltseW@wsdot.wa.gov)> 
Sent: Monday, June 12, 2023 4:30 PM
To: Chinn, Keisha <[chinnk@wsdot.wa.gov](mailto:chinnk@wsdot.wa.gov)>
Subject: FW: fish passage sites mapping

Hi Keisha,

I was wondering if one of your staff members can spend some time with me to go over creating maps and reports using our Tribal Consultation Area and fish passage delivery plan layers?  

Sincerely
Wayne Wiltse

**Comment by jesse-WSDOT** [comment]
Task complete
