### ISSUE TITLE
GIS Request for Tribal U&A Map

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#313]
Wayne Wiltse also requested help with a different project in same email as his other:

> "I also have another potential project, I have confidential Tribal U&A maps and was wondering if a GIS layer can be created for me using the maps and still keep the information confidential, with this layer only being viewable by myself or other WSDOT Tribal Liaisons?"

I don't see any issue with sharing this confidential information since it will only be for internal use by those who should already have access to this information, being Tribal Liaisons. Unsure if he has an mxd or something else for the Tribal U&A map, might need to re-create something depending.

**Comment by jesse-WSDOT** [comment]
Update: Helped Wanye with geoprocessing data for reports.  Will follow-up with him in a few weeks to see if additional analysis is required.  Closing task.
