### ISSUE TITLE
DAHP’s datashare Q3

### ISSUE THREAD

**Issue by jesse-WSDOT** [wsdot-eso/Environmental-Information#331]
Downloaded recent DAHP data to I:\DATA\ExternalData\DAHP\20231101_NEW

Let me know if you need any assistance.

**Comment by jesse-WSDOT** [comment]
Any updates with DAHP?

**Comment by gfuellingwa** [comment]
I ran the deployment script around 5 but doesn't seem to have run yet. Might need Jordyn to run it. Data is in prep environment with updated metadata date.
