### ISSUE TITLE
Issue with Spotted Owl Nesting Site (PHS) layer in GIS Workbench

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#333]
Something maybe went weird with last PHS update, or sometime after somehow. Need to look into what is going on with this "Spotted Owl Nesting Site" layer, which pulls in symbology but no data. Both Kevin White and Jeff who mention it have access to sensitive data layers, so that shouldn't be the issue. I checked the source, and it appears to pointing to the correct biological SRA, same as the other sensitive spotted owl territory layer, which does draw fine.

From: Dreier, Jeff <DreierJ@wsdot.wa.gov> 
Sent: Tuesday, December 12, 2023 10:57 AM
To: Chinn, Keisha <chinnk@wsdot.wa.gov>
Cc: Kapantais, Katina <KapantK@wsdot.wa.gov>; Toal, Kimberly <ToalKi@wsdot.wa.gov>
Subject: FW: Workbench Spotted Owl Nest layer - no attributes

Hi Keisha,

I noticed this last week. This is one of the sensitive layers.

Thanks,

Jeff 

From: White, Kevin <[WhiteK@wsdot.wa.gov](mailto:WhiteK@wsdot.wa.gov)> 
Sent: Tuesday, December 12, 2023 7:24 AM
To: Kapantais, Katina <[KapantK@wsdot.wa.gov](mailto:KapantK@wsdot.wa.gov)>; Dreier, Jeff <[DreierJ@wsdot.wa.gov](mailto:DreierJ@wsdot.wa.gov)>
Subject: Workbench Spotted Owl Nest layer - no attributes

Hi Katina and Jeff,
   The spotted owl nest site layer on the workbench doesn’t populate owl nest sites anymore (it used to). The attribute table is blank and has no data with that layer. The owl territory layer populates but not the nest site layer. 

Kevin White
WSDOT SCR –Biologist
[WhiteK@wsdot.wa.gov](mailto:WhiteK@wsdot.wa.gov)
Cell: (509) 260-0383

**Comment by Tjohnson-WSDOT** [comment]
I checked the data in catalog and it doesn't have any records either. Next step is to check original data.

**Comment by Tjohnson-WSDOT** [comment]
The original data has 1269 records.  I don't see a dataset where Garrett did his work so I can't check that data.

**Comment by jesse-WSDOT** [comment]
Replaced SPS dataset with most recent PHS download.  Ran Deployment Script to replace dataset with data on 17P_Edit. 
(not sure ETL is working, but will check later today for update)

**Comment by kechinn** [comment]
Tanya checked and it is working again. Will email Jeff.
