### ISSUE TITLE
Drone Flights for Fish Passage/Stream Restoration Program 2020

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#42]
- [x] Minter Creek and Little Minter Creek (bridge pour video and site virtual tour 7/07/2020)
- [ ] Purdy Spit Bridge
- [x] Coffee Creek - Sept-Oct 2020 post-construction monitoring time frame and once annually to Year 5 (2024) during March-July time frame
- [ ] Tawes Creek North trib - post-construction monitoring. Spring-Summer 2020 time frame, and repeated annually to Year 5 (2024)
- [ ] Buford - one time flight 
- [ ] Rattlesnake - dam blew out upstream a few years ago and ESO to document destruction prior to large scale restoration effort by the Nez Perce Tribe in 2020
- [x] Resort Creek - repeated flight to document subsurface flow conditions pre-post fix. Expanded range. Proposed flights in August to capture low flow period.

Follow up from 2019?:
- [ ] NF Issaquah Creek 
- [ ] WF Hylebos 

Low priority:
- [ ] Oso sites
- [ ] Fisher Creek

**Comment by jesse-WSDOT** [comment]
On hold.

**Comment by jesse-WSDOT** [comment]
Developing workflow to add shapefiles to DroneDeploy.
