### ISSUE TITLE
Glacier Creek Flight #2

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#43]
#12 Need to re-fly Glacier Creek post flooding event in March 2020.

**Comment by jesse-WSDOT** [comment]
Glacier Creek Flight Completed.  Next steps: process and share data to Cygnia.

**Comment by jesse-WSDOT** [comment]
Data processed.  
Waiting on corrected GPS files from vendor.  
Stu will QC.  
Plan to Skype with Cygnia in June.
