### ISSUE TITLE
Resource Conservation Areas

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#72]
**Description:** Check if this needs update/what the plan is for future updates. Determine program owner, if any.
**Category:** Extnrl SDE Data - Update
**Workspace:** 
**% Complete:**

**Comment by Tjohnson-WSDOT** [comment]
Jeff Graham would like to update this data with new links and he will check with Julie Hartwig to see if she has any other updates

**Comment by Tjohnson-WSDOT** [comment]
Checked with Jeff Graham - links still not working and he has not received any updates.
