### ISSUE TITLE
Ecology Facility Sites

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#74]
**Description:** Check if this needs update/what the plan is for future updates. Determine program owner, if any. See WB List for more info, including "Ecology Facility Sites Related Table".
**Category:** Extnrl SDE Data - Update
**Workspace:** 
**% Complete:**

**Comment by gfuellingwa** [comment]
https://geo.wa.gov/datasets/waecy::waecy-facility-site-interactions/explore

Discuss this during next team meeting potentially. Dataset is updated daily.

**Comment by gfuellingwa** [comment]
https://fortress.wa.gov/ecy/gisprod/arcgis/rest/services/GIS/ECYAuthoritativeGISDatasets/MapServer/18

**Comment by gfuellingwa** [comment]
Discuss this next teams meeting/1on1(table of facility interactions is now a point layer).

**Comment by gfuellingwa** [comment]
Email sent

**Comment by gfuellingwa** [comment]
On WB and spreadsheet updated
