### ISSUE TITLE
NHD/major waterbodies

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#76]
**Description:** Check if NHD needs to be updated, and then also determine if non NHD major waterways are needed/deprecated. Major Rivers Major Waterways Major Shorelines. Tanya thinks that the "Major x" datasets are pointing to the NHD datasets, but have definition queries/different symbology.
**Category:** Extnrl SDE Data - **Update**
**Workspace:**  I:\DATA\ExternalData\ECY\Hydro_NHD\Update_20190826
**% Complete:**  75%

**Comment by Tjohnson-WSDOT** [comment]
Compared data in the 2019 folder with workbench.
   2 FC had schema changes -     Coastline and Rivers/Streams
    1 FC had no changes - hydro Pts
     Truncate/Load to 17P - Landmarks, waterbodies, major waterbodies.
Working on updating metadata.

**Comment by Tjohnson-WSDOT** [comment]
I put the draft email and .lyr files in I:\DATA\ExternalData\ECY\Hydro_NHD\Update_20190826\WB_Prep

**Comment by Tjohnson-WSDOT** [comment]
Had meeting with Jesse 7 Jordyn to send .lyr and data ready for workbench.  Emailed updated .lyr to ITD

**Comment by Tjohnson-WSDOT** [comment]
Checked that data on workbench and works. 3/4/2021
