### ISSUE TITLE
Metadata Batch Update

### ISSUE THREAD

**Issue by gfuellingwa** [wsdot-eso/Environmental-Information#82]
Currently have a script that overwrites Credits element but overwrites everything.

Need to:

1. Change the element that is changed
2. Make it so the rest of the metadata is not overwritten

**Comment by jesse-WSDOT** [comment]
Help docs -

[Edit_METADATA_manyArcGISitems.pdf](https://github.com/wsdot-eso/Environmental-Information/files/5783032/Edit_METADATA_manyArcGISitems.pdf)

[https://desktop.arcgis.com/en/arcmap/10.7/manage-data/metadata/editing-metadata-for-many-arcgis-items.htm]

**Comment by gfuellingwa** [comment]
https://docs.python.org/2/library/xml.etree.elementtree.html

**Comment by gfuellingwa** [comment]
Email sent to Jordyn for help on this subject

**Comment by gfuellingwa** [comment]
Jordyn suggested using Metadata Import tool vs metadata import. Also suggested the USGS mp metadata tool to avoid an ARCGIS xml document.
