### ISSUE TITLE
Stormwater Survey123

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#98]
Convert Stormwater field forms to Survey123.
**% Complete:** 40%

**Comment by kechinn** [comment]
SharePoint Progress Log:
Fuelling, Garrett (1/5/2021 2:01 PM): Email sent to pick this back up and get the ball rolling.

**Comment by gfuellingwa** [comment]
Moving this to backlog. Forms are finished, data storage will be figured out closer to the time of implementation. Forms are on Admin account and will still be able to be fine tuned if needed.
