### ISSUE TITLE
FEMA (NFHL) Updates

### ISSUE THREAD

**Issue by kechinn** [wsdot-eso/Environmental-Information#99]
**Description:** Find and post any updates to the NFHL data (by county). For each county, see if there is new or updated NFHL data and add, replace or retire WB data as appropriate. FEMA data download source:
**Category:** Extnrl SDE Data - Update
**Workspace:** I:\DATA\ExternalData\FEMA\NFHL_Update2018
**% Complete:** 90%
[FEMA.zip](https://github.com/wsdot-eso/Environmental-Information/files/5852744/FEMA.zip)

**Comment by kechinn** [comment]
SharePoint Progress Log:
Alton, Jesse (12/23/2020 4:48 PM): Downloaded most recent NFHL dataset(+480) to 17P.  Created new layer for Flood Hazard Zones from https://hazards.fema.gov/gis/nfhl/rest/services/. Need to add missing attribute definitions to metadata.
Johnson, Tanya (12/16/2020 11:09 AM): I updated the .lyr and put the data on EnviroDataEditon17P. Imported and updated the metadata.
Alton, Jesse (10/29/2020 10:16 AM):
Fuelling, Garrett (9/24/2020 12:57 PM): Data is downloaded and critical data has been made into .lyr files. Next Step is getting data oo to workbench
Fuelling, Garrett (9/8/2020 4:51 PM): Reopening this due to Virginia's request for updating the data on the workbench
Alton, Jesse (1/22/2020 2:04 PM):
Fuelling, Garrett (9/9/2019 2:24 PM): All counties with data updated in 2015 or later downloaded. I:\DATA\ExternalData\FEMA\FEMACountyUpdate2019
Alton, Jesse (9/9/2019 1:12 PM):
Alton, Jesse (6/10/2019 11:50 AM):
Alton, Jesse (2/5/2019 1:31 PM):
Ha, Chris (12/18/2018 2:54 PM): Counties with updated (2015+) FEMA NFHL Data have been downloaded from the FEMA Flood Map Center (https://msc.fema.gov/portal/advanceSearch#searchresultsanchor) and placed in I:\DATA\ExternalData\FEMA\NFHL_Update2018\AsDownloaded.
Lanzer, Elizabeth (7/23/2018 9:46 AM):
Lanzer, Elizabeth (7/11/2018 2:26 PM): Attached March 2018 emial regarding NFHL updates in King County - so at least one county has new data!

**Comment by jesse-WSDOT** [comment]
Received MXDs from FEMA.  Sourced FEMA layers (from MXD) to 17P.  Jordyn created new 17P edit DB for NFHL datasets for future ETLs.  Keeping existing Q3 data as "historic".  New NFHL data to post 1st week of Feb.  
Issue: No online GDB download for **Preliminary** NFHL dataset.   Reached out to Jerry Franklin at Ecology for help.  Also - NHFL download missing:
**LOMAs
Topographic Low Confidence Areas
Base Flood Elevations**

**Comment by jesse-WSDOT** [comment]
New NFHL and Q3 data/layers on SDE 19P .  Jordyn will make available on Workbench ASAP.  Preliminary staged on 17PFloodPlain database - need to point new layers once moved to PROD.   Send new NFHL layers to Virginia to review.

**Comment by jesse-WSDOT** [comment]
Prelim layers updated and ready on Workbench
